apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "S:/Github/data-lakehouse-with-delta-lake-using-k8s/minio"
    type: Directory