apiVersion: v1
kind: PersistentVolume
metadata:
  name: notebooks-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "S:/Github/data-lakehouse-with-delta-lake-using-k8s/workspace"
    type: Directory