apiVersion: v1
kind: Service
metadata:
  name: spark-master
spec:
  type: NodePort
  selector:
    app: spark-master
  ports:
  - port: 7077
    targetPort: 7077
    nodePort: 30777
    name: spark
  - port: 8080
    targetPort: 8080
    nodePort: 30808
    name: webui