apiVersion: v1
kind: Service
metadata:
  name: spark-notebook
spec:
  selector:
    app: spark-notebook
  ports:
  - port: 8888
    targetPort: 8888
    name: notebook
  - port: 4040
    targetPort: 4040
    name: spark-ui